version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  migration:
    build:
      context: ./go-tour-migration
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://root:admin123@mongo:27017/go-tour-migration-test?authSource=admin

  application:
    build:
      context: ./go-tour
    depends_on:
      - mongo
      - migration
    environment:
      CONFIG_PATH: "/app/config-dev.yaml"
    ports:
      - "8080:8080"

volumes:
  mongodb_data:

